# docker-compose.yml
version: '3'
services:
  app:
    build: .
    environment:
      JWT_SECRET: ${JWT_SECRET}
      MONGO_URI: ${MONGO_URI}
    ports:
      - "3000:3000"
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
